name: Tests

on:
  push:
    tags-ignore:
      - 'v*.*.*'        

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - run: npm run coverage:report
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  Release:
    needs:
      - build
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      if: github.ref == 'refs/heads/master'
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.0.0
      if: github.ref == 'refs/heads/master'
    - name: Create .npmrc
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: github.ref == 'refs/heads/master'
    - name: Release
      run: npm run release
      if: github.ref == 'refs/heads/master'